execute pathogen#infect()

" Line numbers
set number

" Always show current position
set ruler

set expandtab "tabs to spaces
set tabstop=2 "1 tab = 2 spaces

" Ignore case when searching
set ignorecase

" When searching try to be smart about cases
set smartcase

" Highlight search results
set hlsearch

" Makes search act like search in modern browsers
set incsearch

" Clear last search highlighting
map <Space> :noh<cr>

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" Set utf8 as standard encoding and en_US as the standard language
set encoding=utf8

"Use Unix as the standard file type
set ffs=unix,dos,mac

syntax enable

set cursorline
" Solarized
set background=light
"let g:solarized_termtrans="1"
"let g:solarized_termcolors="256"
"let g:solarized_termcolors="16"
"set background=dark
colorscheme solarized

map <D-1> :NERDTreeToggle<CR>

set autoindent

if has('gui_running')
   set cursorline
   set background=light
else
    set background=light
endif
